"""empty message

Revision ID: 347eb5f8ff15
Revises: 72270e5628c4
Create Date: 2022-10-03 23:06:28.604685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347eb5f8ff15'
down_revision = '72270e5628c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('access_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('cp_wrong', sa.Integer(), nullable=False),
    sa.Column('cp_right', sa.Integer(), nullable=False),
    sa.Column('cap_wrong', sa.Integer(), nullable=False),
    sa.Column('cap_right', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), server_default='0', nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('refered_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['refered_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('quiz_sessions')
    op.drop_table('quiz_questions')
    op.drop_table('courses')
    # ### end Alembic commands ###
